language: python
sudo: false
matrix:
    include:
        - python: "2.7"
        - python: "3.6"
        - python: "3.7"
          dist: xenial
install:
    - pip install -r https://raw.githubusercontent.com/plone/buildout.coredev/5.2/requirements.txt
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
